-- MySQL Script generated by MySQL Workbench
-- Thu May  6 20:42:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema healthlab
-- -----------------------------------------------------

DROP DATABASE healthlab;

-- -----------------------------------------------------
-- Schema healthlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `healthlab` DEFAULT CHARACTER SET utf8 ;
USE `healthlab` ;

-- -----------------------------------------------------
-- Table `healthlab`.`residents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`residents` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`residents` (
  `residents_create_date` DATETIME NOT NULL,
  `residents_id` INT NOT NULL AUTO_INCREMENT,
  `residents_name` VARCHAR(300) NOT NULL,
  `residents_surname` VARCHAR(300) NOT NULL,
  `residents_gender` VARCHAR(300) NOT NULL,
  `residents_birth_date` VARCHAR(300) NOT NULL,
  `residents_identity` VARCHAR(300) NOT NULL,
  `residents_tell` VARCHAR(300) NOT NULL,
  `residents_zip_code` VARCHAR(300) NOT NULL,
  `residents_address` VARCHAR(300) NOT NULL,
  `residents_district` VARCHAR(300) NOT NULL,
  `residents_city` VARCHAR(300) NOT NULL,
  `residents_state` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`residents_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `healthlab`.`Clinics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Clinics` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Clinics` (
  `clinic_create_date` DATETIME NOT NULL,
  `clinic_id` INT NOT NULL AUTO_INCREMENT,
  `clinic_name` VARCHAR(300) NOT NULL,
  `clinic_description` VARCHAR(2400) NOT NULL,
  PRIMARY KEY (`clinic_id`))
ENGINE = InnoDB;

insert into healthlab.clinics values (now(), null, 'medicina','Atendimento médico a partir de 14 anos. É preciso que a primeira consulta médica seja marcada pelo posto de saúde/SUS da Regional Oeste ou de Nova Lima.');
insert into healthlab.clinics values (now(), null, 'odontologia','Os atendimentos são nas áreas de cirurgia, laserterapia, raspagem, limpeza, periodontal (gengiva), restaurações, radiografia e tratamentos preventivos como fluoterapia e odontopediatria.');
insert into healthlab.clinics values (now(), null, 'fisioterapia','A fisioterapia atua em dois ciclos nas seguintes áreas neurologia, cardiologia e respiratória no primeiro ciclo e ortopedia, saúde da mulher e gerontologia no segundo ciclo, objetivando a melhora da qualidade de vida, o retorno do indivíduo às suas práticas do dia-a-dia e favorecendo a participação social.');
insert into healthlab.clinics values (now(), null, 'nutrição','Atendimento em todas as áreas clínicas da nutrição com diagnóstico e tratamento, entre eles a pediatria, obesidade, controle alimentar, gestante, idosos e praticantes de atividade física ou exercício físico. É necessário o encaminhamento do médico do SUS.');
insert into healthlab.clinics values (now(), null, 'psicologia','Os atendimentos, são para todas as idades e estão sendo realizados de forma online mediante pandemia. Os interessados no processo terapêutico, podem agendar atendimento mediante cadastro no portal do Unibh de forma online.');

-- -----------------------------------------------------
-- Table `healthlab`.`Specialties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Specialties` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Specialties` (
  `specialty_create_date` DATETIME NOT NULL,
  `specialty_id` INT NOT NULL AUTO_INCREMENT,
  `specialty_name` VARCHAR(300) NOT NULL,
  `specialty_description` VARCHAR(2400) NOT NULL,
  `specialty_clinic_id` INT NOT NULL,
  PRIMARY KEY (`specialty_id`),
  INDEX `fk_Specialties_Clinics1_idx` (`specialty_clinic_id` ASC) VISIBLE,
  CONSTRAINT `fk_Specialties_Clinics1`
    FOREIGN KEY (`specialty_clinic_id`)
    REFERENCES `healthlab`.`Clinics` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#medicina
insert into healthlab.specialties values (now(), null, 'Angiologia','Tratamento clínico para doenças que afetam os vasos sanguíneos e linfáticos.',1);
insert into healthlab.specialties values (now(), null, 'Cardiologia','Especialidade responsável para o tratamento de doenças que acometem o coração e o sistema circulatório.',1);
insert into healthlab.specialties values (now(), null, 'Dermatologia','Diagnóstico, tratamento e prevenção de doenças da pele, pelos, mucosas, cabelos e unhas.',1);
insert into healthlab.specialties values (now(), null, 'Endocrinologia','Cuida do funcionamento das glândulas e das doenças que as afetam.',1);
insert into healthlab.specialties values (now(), null, 'Gastroenterologia','Especialidade médica responsável por diagnosticar,prevenir e tratar problemas não cirúrgicos no aparelho digestivo.',1);
insert into healthlab.specialties values (now(), null, 'Geriatria','Estudo, a prevenção e o tratamento de doenças e da terceira idade.',1);
insert into healthlab.specialties values (now(), null, 'Neurologia','Diagnóstico e tratamento de doenças no cérebro, medula espinhal (sistema nervoso central) e nervos periféricos.',1);
insert into healthlab.specialties values (now(), null, 'Ortopedia','Especialidade médica que cuida da saúde relacionadas aos elementos do aparelho locomotor, como ossos, músculos, ligamentos e articulações.',1);
insert into healthlab.specialties values (now(), null, 'Pneumologia','Responsável pelo tratamento das patologias das vias aéreas inferiores.',1);
insert into healthlab.specialties values (now(), null, 'Reumatologia','Se ocupa do estudo das doenças que acometem os tecidos conjuntivos, que incluem as articulações, os ossos, os músculos, os tendões e os ligamentos, as chamadas doenças reumáticas.',1);
insert into healthlab.specialties values (now(), null, 'Otorrinolaringologia','Se dedica ao estudo e tratamento das doenças que acometem a orelha, o nariz e a garganta.',1);
insert into healthlab.specialties values (now(), null, 'Urologia','Especialidade cirúrgica da medicina que trata do trato urinário de homens e de mulheres e do sistema reprodutor das pessoas do sexo masculino.',1);

#Odontologia
insert into healthlab.specialties values (now(), null, 'Odontopediatria','Atua diretamente na prevenção, reabilitação e manutenção da saúde bucal infantil.',2);
insert into healthlab.specialties values (now(), null, 'Cirurgia','Tratamento cirúrgico de problemas relacionados aos dentes, ossos, gengivas, lábios, língua e bochechas.',2);
insert into healthlab.specialties values (now(), null, 'Periodontia','É a área da saúde que previne e trata as doenças que acomete a gengiva e os tecidos de inserção do dente.',2);
insert into healthlab.specialties values (now(), null, 'Estomatologia','Objetivo de prevenção, diagnóstico, tratamento e acompanhamento das lesões bucais.',2);
insert into healthlab.specialties values (now(), null, 'Endodontia','Responsável pelo estudo da polpa dentária, de todo o sistema de canais radiculares e dos tecidos periapicais.',2);
insert into healthlab.specialties values (now(), null, 'Prótese','Reabilitação da cavidade oral, substitui artificialmente os dentes perdidos de toda uma arcada dentária.',2);
insert into healthlab.specialties values (now(), null, 'Profilaxia','O objetivo da profilaxia é manter a boca saudável e evitar riscos de doenças periodontais e bucais.',2);

#fisioterapia
insert into healthlab.specialties values (now(), null, 'Ortopédica','Atua no alívio da dor, no restabelecimento de funções, no aumento da força muscular, na correção de deformidades e também na prevenção de lesões.',3);
insert into healthlab.specialties values (now(), null, 'Gerontologia','Previne e trata enfermidades decorrentes do processo do envelhecimento, promovendo a recuperação de pessoas idosas.',3);
insert into healthlab.specialties values (now(), null, 'Saúde da Mulher','Ampla atuação fisioterapêutica ao longo do ciclo vital feminino: na infância, na gravidez, no trabalho de parto, no pós-parto, no puerpério, no climatério e na terceira idade.',3);
insert into healthlab.specialties values (now(), null, 'Neurofuncional','Atua de forma preventiva, adaptativa ou paliativa nas sequelas resultantes de danos ao Sistema Nervoso, abrangendo tanto o Sistema Nervoso Central como o Periférico.',3);
insert into healthlab.specialties values (now(), null, 'Cardiológica ','Atua na prevenção e ao tratamento das doenças cardíacas através do exercício físico.',3);
insert into healthlab.specialties values (now(), null, 'Respiratória','Atua na prevenção e no tratamento de doenças que atingem o sistema respiratório, trazendo uma melhor qualidade de vida como a asma, bronquite, insuficiência respiratória e tuberculose.',3);

#Nutrição
insert into healthlab.specialties values (now(), null, 'Materno-Infantil','Atua em etapas distintas da vida da mulher,como na tentativa de engravidar,durante a gestação e na própria nutrição da mãe e do bebê.',4);
insert into healthlab.specialties values (now(), null, 'Obesidade','Avaliação do estado nutricional do paciente diante do diagnóstico nutricional e das necessidades nutricionais,visando promover melhora na saúde e composição corporal.',4);
insert into healthlab.specialties values (now(), null, 'Idoso','Monitoramento da situação alimentar e nutricional dos idosos,promovendo ações de práticas alimentares saudáveis e prevenção e controle de distúrbios nutricionais.',4);
insert into healthlab.specialties values (now(), null, 'Nutrição Esportiva','Promove melhora na performance e um aumento no rendimento dos  praticantes de atividade física ou exercício físico,buscando  ingestão equilibrada de todos os nutrientes.',4);

#psicologia
insert into healthlab.specialties values (now(), null, 'Terapia','',5);

-- -----------------------------------------------------
-- Table `healthlab`.`Schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Schedules` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Schedules` (
  `scheduling_create_date` DATETIME NOT NULL,
  `scheduling_id` INT NOT NULL AUTO_INCREMENT,
  `scheduling_date` DATETIME NOT NULL,
  `scheduling_weekday` VARCHAR(300) NOT NULL,
  `scheduling_time` VARCHAR(300) NOT NULL,
  `scheduling_queue` TINYINT NOT NULL,
  `scheduling_terms` TINYINT NOT NULL,
  `scheduling_status` INT NOT NULL,
  `scheduling_patient_id` INT NOT NULL,
  `scheduling_clinic_id` INT NOT NULL,
  `scheduling_specialties_id` INT NOT NULL,
  PRIMARY KEY (`scheduling_id`),
  INDEX `fk_Appointment_Patiants1_idx` (`scheduling_patient_id` ASC) VISIBLE,
  INDEX `fk_Appointment_Clinics1_idx` (`scheduling_clinic_id` ASC) VISIBLE,
  INDEX `fk_Appointment_Specialties1_idx` (`scheduling_specialties_id` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Patiants1`
    FOREIGN KEY (`scheduling_patient_id`)
    REFERENCES `healthlab`.`Patiants` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Clinics1`
    FOREIGN KEY (`scheduling_clinic_id`)
    REFERENCES `healthlab`.`Clinics` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Specialties1`
    FOREIGN KEY (`scheduling_specialties_id`)
    REFERENCES `healthlab`.`Specialties` (`specialty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `healthlab`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Users` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Users` (
  `user_create_date` DATETIME NOT NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(300) NOT NULL UNIQUE,
  `user_password` VARCHAR(300) NOT NULL,
  `user_type` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

insert into healthlab.Users values (now(), null, 'admin@teste.com','password','admin');
insert into healthlab.Users values (now(), null, 'rafela@prof.com','password','teacher');
insert into healthlab.Users values (now(), null, 'flavio@prof.com','password','teacher');
insert into healthlab.Users values (now(), null, 'lucas@prof.com','password','teacher');
insert into healthlab.Users values (now(), null, 'leandro@prof.com','password','teacher');
insert into healthlab.Users values (now(), null, 'wagner@prof.com','password','teacher');

-- -----------------------------------------------------
-- Table `healthlab`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Teachers` (
  `teacher_create_date` DATETIME NOT NULL,
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `teacher_name` VARCHAR(300) NOT NULL,
  `teacher_identity` VARCHAR(300) NOT NULL,
  `teacher_user_id` INT NOT NULL,
  `teacher_clinic_id` INT NOT NULL,
  PRIMARY KEY (`teacher_id`),
  INDEX `fk_Teachers_Employees1_idx` (`teacher_user_id` ASC) VISIBLE,
  INDEX `fk_Teachers_Clinics1_idx` (`teacher_clinic_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers_Employees1`
    FOREIGN KEY (`teacher_user_id`)
    REFERENCES `healthlab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_Clinics1`
    FOREIGN KEY (`teacher_clinic_id`)
    REFERENCES `healthlab`.`Clinics` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into healthlab.Teachers values (now(), null, 'Rafaela',123,2,1);
insert into healthlab.Teachers values (now(), null, 'Flavio',124,3,2);
insert into healthlab.Teachers values (now(), null, 'Lucas',125,4,3);
insert into healthlab.Teachers values (now(), null, 'Leandro',126,5,4);
insert into healthlab.Teachers values (now(), null, 'Wagner',127,6,5);

-- -----------------------------------------------------
-- Table `healthlab`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Students` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Students` (
  `student_create_date` DATETIME NOT NULL,
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(300) NOT NULL,
  `student_identity` VARCHAR(300) NOT NULL,
  `student_user_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_Students_Employees1_idx` (`student_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Employees1`
    FOREIGN KEY (`student_user_id`)
    REFERENCES `healthlab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `healthlab`.`Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Classes` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Classes` (
  `class_create_date` DATETIME NOT NULL,
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(300) NOT NULL,
  `class_year` INT NOT NULL,
  `class_semester` VARCHAR(300) NOT NULL,
  `class_appointments` INT NOT NULL,
  `class_queue` TINYINT NOT NULL,
  `class_times` VARCHAR(1200) NOT NULL,
  `class_specialties_id` INT NOT NULL,
  `class_clinic_id` INT NOT NULL,
  `class_teacher_id` INT NOT NULL,
  PRIMARY KEY (`class_id`),
  INDEX `fk_Classes_Specialties1_idx` (`class_specialties_id` ASC) VISIBLE,
  INDEX `fk_Classes_Clinics1_idx` (`class_clinic_id` ASC) VISIBLE,
  INDEX `fk_Classes_Teachers1_idx` (`class_teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Classes_Specialties1`
    FOREIGN KEY (`class_specialties_id`)
    REFERENCES `healthlab`.`Specialties` (`specialty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classes_Clinics1`
    FOREIGN KEY (`class_clinic_id`)
    REFERENCES `healthlab`.`Clinics` (`clinic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Classes_Teachers1`
    FOREIGN KEY (`class_teacher_id`)
    REFERENCES `healthlab`.`Teachers` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `healthlab`.`Class_Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Class_Schedule` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Class_Schedule` (
  `cs_id` INT NOT NULL AUTO_INCREMENT,
  `cs_date` DATE NOT NULL,
  `cs_year` INT NOT NULL,
  `cs_month` INT NOT NULL,
  `cs_weekday` VARCHAR(45) NOT NULL,
  `cs_day` INT NOT NULL,
  `cs_hour` INT NOT NULL,
  `cs_number_students_available` INT NOT NULL,
  `cs_queue` INT NOT NULL,
  `cs_active` TINYINT NOT NULL,
  `cs_class_id` INT NOT NULL,
  INDEX `fk_Class_Schedules_Classes1_idx` (`cs_class_id` ASC) VISIBLE,
  PRIMARY KEY (`cs_id`),
  CONSTRAINT `fk_Class_Schedules_Classes1`
    FOREIGN KEY (`cs_class_id`)
    REFERENCES `healthlab`.`Classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `healthlab`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `healthlab`.`Employees` ;

CREATE TABLE IF NOT EXISTS `healthlab`.`Employees` (
  `employee_create_date` DATETIME NOT NULL,
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(300) NOT NULL,
  `employee_identity` VARCHAR(300) NOT NULL,
  `employee_user_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employees_Users1_idx` (`employee_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Users1`
    FOREIGN KEY (`employee_user_id`)
    REFERENCES `healthlab`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into healthlab.Employees values (now(), null, 'João Pedro', 147, 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
